COLORS = {
    # Core semantic colors (18 base colors)
    "color-black": "#000000",
    "color-on-black": "#ffffff",
    "color-white": "#ffffff",
    "color-on-white": "#000000",
    "color-primary": "#006b5f",
    "color-on-primary": "#ffffff",
    "color-primary-container": "#9ef2e3",
    "color-on-primary-container": "#005048",
    "color-secondary": "#4a635e",
    "color-on-secondary": "#ffffff",
    "color-secondary-container": "#cce8e2",
    "color-on-secondary-container": "#334b47",
    "color-tertiary": "#456179",
    "color-on-tertiary": "#ffffff",
    "color-tertiary-container": "#cbe6ff",
    "color-on-tertiary-container": "#2d4a60",
    "color-error": "#ba1a1a",
    "color-on-error": "#ffffff",
    "color-error-container": "#ffdad6",
    "color-on-error-container": "#93000a",
    "color-surface": "#f4fbf8",
    "color-on-surface": "#3f4946",
    "color-surface-dim": "#d5dbd9",
    "color-on-surface-dim": "#161d1b",

    # Utility states
    "color-info": "#27638a",
    "color-on-info": "#ffffff",
    "color-success": "#3b6939",
    "color-on-success": "#ffffff",
    "color-warning": "#685f12",
    "color-on-warning": "#ffffff",
    "color-outline": "#6f7976",
}